import type { JsonValue } from '..';
import {
  combine as _combine,
  deserialize as _deserialize,
  generatePermutations as _generatePermutations,
  getPrecomputed as _getPrecomputed,
  serialize as _serialize,
} from '../engine/precompute';
import type { Flag, FlagsArray } from './types';

type ValuesArray = readonly any[];

/**
 * Resolves a list of flags.
 * This is SvelteKit-specific because it calls flags with a Request argument.
 * @param flags - list of flags
 * @param request - the SvelteKit request
 * @returns an array of evaluated flag values with one entry per flag
 */
async function evaluate<T extends FlagsArray>(
  flags: T,
  request: Request,
): Promise<{ [K in keyof T]: Awaited<ReturnType<T[K]>> }> {
  return Promise.all(flags.map((flag) => flag(request))) as Promise<{
    [K in keyof T]: Awaited<ReturnType<T[K]>>;
  }>;
}

/**
 * Evaluate a list of feature flags and generate a signed string representing their values.
 *
 * This convenience function call combines `evaluate` and `serialize`.
 *
 * @param flags - list of flags
 * @returns a string representing evaluated flags
 */
export async function precompute<T extends FlagsArray>(
  flags: T,
  request: Request,
  secret: string,
): Promise<string> {
  const values = await evaluate(flags, request);
  return _serialize(flags, values, secret);
}

/**
 * Decodes the value of a flag given the list of flags used to encode and the code.
 *
 * @param flagKey - Flag key to decode
 * @param precomputeFlags - Flags used when `code` was generated by `serialize`
 * @param code - The code returned from `serialize`
 * @param secret - The secret to use for verifying the signature
 */
export async function getPrecomputed<T extends JsonValue>(
  flagKey: Flag<T>['key'],
  precomputeFlags: FlagsArray,
  code: string,
  secret: string,
): Promise<T> {
  // SvelteKit's getPrecomputed takes a key string, so we create a minimal flag-like object
  const flagLike = { key: flagKey };
  return _getPrecomputed(flagLike, precomputeFlags, code, secret);
}

/**
 * Generates all permutations given a list of feature flags based on the options declared on each flag.
 * @param flags - The list of feature flags
 * @param filter - An optional filter function which gets called with each permutation.
 * @param secret - The secret to sign the generated permutation with
 * @returns An array of strings representing each permutation
 */
export async function generatePermutations(
  flags: FlagsArray,
  filter: ((permutation: Record<string, JsonValue>) => boolean) | null = null,
  secret: string,
): Promise<string[]> {
  return _generatePermutations(flags, filter, secret);
}
