import type { JsonValue } from '..';
import * as shared from '../shared/precompute';
import { evaluate } from './evaluate';
import type { Flag, FlagsArray } from './types';

type ValuesArray = readonly any[];

/**
 * Evaluate a list of feature flags and generate a signed string representing their values.
 *
 * This convenience function call combines `evaluate` and `serialize`.
 *
 * @param flags - list of flags
 * @returns - a string representing evaluated flags
 */
export async function precompute<T extends FlagsArray>(
  flags: T,
  request: Request,
  secret: string,
): Promise<string> {
  const values = await evaluate(flags, request, secret);
  return serialize(flags, values, secret);
}

/**
 * Takes a list of feature flag declarations and their values and turns them into a short, signed string.
 *
 * The returned string is signed to avoid enumeration attacks.
 *
 * When a feature flag's `options` contains the value the flag resolved to, then the encoding will store it's index only, leading to better compression. Boolean values and null are compressed even when the options are not declared on the flag.
 *
 * @param flags - A list of feature flags
 * @param values - A list of the values of the flags declared in ´flags`
 * @param secret - The secret to use for signing the result
 * @returns - A short string representing the values.
 */
async function serialize(
  flags: FlagsArray,
  values: ValuesArray,
  secret: string,
) {
  return shared.serialize(flags, values, secret);
}

/**
 * Decodes all flags given the list of flags used to encode. Returns an object consisting of each flag's key and its resolved value.
 * @param flags - Flags used when `code` was generated by `precompute` or `serialize`.
 * @param code - The code returned from `serialize`
 * @param secret - The secret to use for signing the result
 * @returns - An object consisting of each flag's key and its resolved value.
 */
async function deserialize(flags: FlagsArray, code: string, secret: string) {
  return shared.deserialize(flags, code, secret);
}

/**
 * Decodes the value of one or multiple flags given the list of flags used to encode and the code.
 *
 * @param flagKey - Flag or list of flags to decode
 * @param precomputeFlags - Flags used when `code` was generated by `serialize`
 * @param code - The code returned from `serialize`
 * @param secret - The secret to use for verifying the signature
 */
export async function getPrecomputed<T extends JsonValue>(
  flagKey: Flag<T>['key'],
  precomputeFlags: FlagsArray,
  code: string,
  secret: string,
): Promise<T> {
  if (code === '__no_flags__') {
    shared.warnEmptyCode(flagKey);
  }

  const flagSet = await deserialize(precomputeFlags, code, secret);

  return shared.readFlagValue(flagSet, flagKey);
}

/**
 * Generates all permutations given a list of feature flags based on the options declared on each flag.
 * @param flags - The list of feature flags
 * @param filter - An optional filter function which gets called with each permutation.
 * @param secret - The secret sign the generated permutation with
 * @returns An array of strings representing each permutation
 */
export async function generatePermutations(
  flags: FlagsArray,
  filter: ((permutation: Record<string, JsonValue>) => boolean) | null = null,
  secret: string,
): Promise<string[]> {
  return shared.generatePermutations(flags, filter, secret);
}
