packages:
  - packages/*
  - tests/*
  - examples/*
  - apps/*

catalog:
  '@types/react': ^19
  '@types/react-dom': ^19

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - 'flags'
  - '@flags-sdk/*'
  - '@vercel/*'

