import type { JsonValue } from '.';
import * as s from './lib/serialization';

type FlagsArray = readonly s.CommonFlag<any>[];

/**
 * Decodes the value of a single flag given the list of flags used to encode and the code.
 *
 * @param flagKey - Flag or list of flags to decode
 * @param precomputeFlags - Flags used when `code` was generated by `serialize`
 * @param code - The code returned from `serialize`
 * @param secret - The secret to use for verifying the signature
 */
export async function getPrecomputed<T extends JsonValue>(
  flagKey: s.CommonFlag<T>['key'],
  precomputeFlags: FlagsArray,
  code: string,
  secret: string,
): Promise<T> {
  const flagSet = await deserialize(precomputeFlags, code, secret);

  return flagSet[flagKey];
}

/**
 * Decodes all flags given the list of flags used to encode. Returns an object consisting of each flag's key and its resolved value.
 * @param flags - Flags used when `code` was generated by `serialize`.
 * @param code - The code returned from `serialize`
 * @param secret - The secret to use for verifying the signature
 * @returns - An object consisting of each flag's key and its resolved value.
 */
async function deserialize(flags: FlagsArray, code: string, secret: string) {
  return s.deserialize(code, flags, secret);
}
